name: 'Save organisation secret'
description: 'Encrypts and saves a secret value to an organisation'
author: '@tobiwein'

inputs:
  token:
    description: 'GitHub access token for authorization. Needs the admin:org scope.'
    required: true
  githubApi:
    description: 'URL of the REST-API of your organization.'
    default: ''
  organisation:
    description: 'The name of the organisation. The name is not case sensitive.'
    required: true
  secret:
    description: 'The secret value that you want to store.'
    required: true
  secretName:
    description: 'The name of the secret the value should be stored in.'
    required: true

runs:
  using: node20
  main: index.js
