name: 'Save repository secret'
description: 'Encrypts and saves a secret value to a repository'
author: '@tobiwein'

inputs:
  token:
    description: 'GitHub access token for authorization.'
    required: true
  githubApi:
    description: 'URL of the REST-API of your organization.'
    default: ''
  repositoryName:
    description: 'The name of the repository without the .git extension.'
    required: true
  repositoryOwner:
    description: 'The account owner of the repository.'
    required: true
  secret:
    description: 'The secret value that you want to store.'
    required: true
  secretName:
    description: 'The name of the secret the value should be stored in.'
    required: true

runs:
  using: node20
  main: index.js
